###################
#  GoCV + OpenCV  #
###################
FROM gocv/opencv:4.5.0-gpu AS gocv-gpu-test
LABEL maintainer="hybridgroup"

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv
WORKDIR /go/src/gocv.io/x/gocv

RUN go build -tags example -o /build/gocv_cuda_version ./cmd/cuda/

CMD ["/build/gocv_cuda_version"]
