###################
#  GoCV + OpenCV  #
###################
FROM gocv/opencv:4.5.0-gpu
LABEL maintainer="hybridgroup"

ENV GOPATH /go
WORKDIR $GOPATH

RUN go get -u -d gocv.io/x/gocv

WORKDIR ${GOPATH}/src/gocv.io/x/gocv/cmd/cuda/

RUN go build -o gocv_cuda_version -i main.go

CMD ["./gocv_cuda_version"]
